### ISSUE TITLE
Integration in Silex Framework

### ISSUE THREAD

**Issue by Brah0um** [bruli/php-git-hooks#13]
Hi,
I would like to use your hook with the Silex Framework.
When I try to commit, the pre-commit hook doesn't work because the binaries aren't found in the bin directory.
In my Silex project, I found the binaries under vendor/bin directory.
What should I do? Is there a way to update the binary path?

Thanks

**Comment by bruli** [comment]
Hi.

I updated README.md file.
You can see the answer in it.

Thanks.

**Comment by Brah0um** [comment]
It works great !

Thanks a lot !
