### ISSUE TITLE
OS X Using wrong php

### ISSUE THREAD

**Issue by aequasi** [bruli/php-git-hooks#14]
I fixed this on mine by just symlinking the homebrew php to `/usr/bin/php`. Not sure if thats the right way to do it, but it worked for me. Might be worth throwing in the readme?

**Comment by bruli** [comment]
What's the problem?. Don't works the command in your environment?

**Comment by aequasi** [comment]
It starts to use extensions for the wrong version of php. Its really weird. I'm not sure exactly what its doing, or why its doing it.

**Comment by aequasi** [comment]
You can close if you dont want to deal with it lol
