### ISSUE TITLE
Files not in src

### ISSUE THREAD

**Issue by quentincurtet** [bruli/php-git-hooks#19]
Hi,

I am working on a project, but i want to check some php files which are not in src/ folder.
I am working in my vendor so there is no src/ folder.

How can i do to check all php files in my vendor/myproject/my-bundle/ ?

Thanks

**Comment by quentincurtet** [comment]
UP
Can someone help me ?

**Comment by patxi1980** [comment]
I thing the best way to achieve, is to have src inside your project in vendor, so you can install php-git-hooks in your vendor project, not in all the project. 

So your git is only in your vendor project (usually, vendors is not inside your git).

Your vendor project look like /vendor/myproject/src/my-bundle

And you can then have installed the php-git-hooks in vendor/myproject

I hope it helps

**Comment by quentincurtet** [comment]
It is not possible, it will break the established namespace.

But the problem is : bruli defined the src folder for git hooks but i would like to change src by another folder like myFolder in vendor/myProject/my-bundle/myFolder.

Thanks

**Comment by quentincurtet** [comment]
If it is not possible just tell it to me
Because i need to use php-git-hooks but i can't because i don't have a src folder in my project

**Comment by nilopc** [comment]
@quentincurtet why not creating a soft link named src?

**Comment by quentincurtet** [comment]
It is not a bad idea but when i want to commit, the path of my file is not src/myFile, it is always "myFIle.php".

HOw can i do to change the path in my git status ?
