### ISSUE TITLE
PHPCS Warnings

### ISSUE THREAD

**Issue by jdgriffith** [bruli/php-git-hooks#20]
Great package btw! Love what this does out of the box.

Is it possible for the codesniffer to pass when there are just warnings? In my current codebase, the codesniffer gripes about line length, but the PSR2 standard does not have a hard limit.

**Comment by bruli** [comment]
If  codesniffer shows warnings, it's because your code style is not correct. This is the goal of this tool.

PSR2 standard have a soft limit to 120 characters. You can configure your IDE to see all code style errors.

**Comment by jdgriffith** [comment]
Thanks for the response!

Still curious though.. is it possible (not even just in reference to codesniffer but to other processes) to not fail on warnings?

**Comment by bruli** [comment]
Now not it's possible. Warnings messages are information about incorrect code styles.
