### ISSUE TITLE
Support custom PHP-CS-Fixer config (.php_cs)

### ISSUE THREAD

**Issue by phofmann-trust** [bruli/php-git-hooks#21]
It would be great if php-git-hooks would support custom configurations for PHP-CS-Fixer. So it should omit passing "--fixers=-psr0" if it detects a .php_cs or .php_cs.dist file.

**Comment by bruli** [comment]
Available in next 2.0 version.
In few days I will publish it.

**Comment by phofmann-trust** [comment]
Thanks for the quick changes!

How do I have to configure php-hit-hooks, so that php-cs-fixer will read the .php_cs or .php_cs.dist file?

The only changes I've seen are, that I can now pass a custom level. Do I have to maintain my list of fixers in php-git-hooks.yml and .php_cs now? (I want to be able to run the php-cs-fixer without committing.)

**Comment by bruli** [comment]
You will can write level option in php-git-hooks.yml file.

**Comment by phofmann-trust** [comment]
But how can I specify a list of fixers? The levels don't match the coding guidelines of my project. :(

**Comment by bruli** [comment]
Since 2.1 version  you can use various levels with php-cs-fixer.

**Comment by phofmann-trust** [comment]
I keep running into problems with php-cs-fixer and php-git-hooks. I think it would be best, if php-git-hooks would support running php-cs-fixer without passing a "level". This would have multiple benefits:
 - Performance improvements, because php-cs-fixer only needs to be run once, and can use the cache file (.php_cs.cache) if configured
 - No duplicate configuration required. At the moment I need to maintain my php-cs-fixer configuration in .php_cs (for running php-cs-fixer without comitting) and php-git-hooks.yml (for the checks that run on commit).

**Comment by phofmann-trust** [comment]
@bruli Can you reopen this issue? Should I create a new one? Or implement this and create a PR? What do you think?

**Comment by bruli** [comment]
You can create a PR.

Thanks.
