### ISSUE TITLE
Hard dependencies

### ISSUE THREAD

**Issue by vpassapera** [bruli/php-git-hooks#23]
Since I use versioneye for my projects as such, when there are outdated dependecies, the service screams. Currently, all the deps in your project are hardcoded to specific versions such as `1.9.*`

To make this forward compatible, especially if there are newer versions, I'd go with something like `~1`

And use Travis or another CI service to ensure that a matrix of versions builds correctly.

**Comment by bruli** [comment]
Ok, thanks
