### ISSUE TITLE
Run tests on bare repository

### ISSUE THREAD

**Issue by tophsic** [bruli/php-git-hooks#29]
I would like to run such check on a bare git repository. I pretty new in git hooks.

Is php-git-hook suitable for such things? If so, how to do it?

**Comment by bruli** [comment]
I'm not sure you understood. You can init a new git repository and intall php-git-hooks and use it.

**Comment by tophsic** [comment]
I admin a Gitlab instance in my company and would like to run php-git-hooks on pre-receive hooks. It works a different way as the pre-commit hook.

Do you think it could be possible to a pre-receive hook?

**Comment by bruli** [comment]
In git (version 2.1.4) not exist a pre-receive hook. Wich is the goal of this hook?.

**Comment by tophsic** [comment]
This is a server-side hook https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks.

I will try to propose you a PR as soon as possible and a description on how I applied it in my company.

**Comment by bruli** [comment]
Php-git-hooks is a client hooks library to use in  php development project. 
Maybe a server git hooks should be a diferent project, because to use webhooks (in github and bitbucket), it needs a url.

But you can feel free to send a PR for this and I will review it.
