### ISSUE TITLE
php minimum version requirement

### ISSUE THREAD

**Issue by maschmann** [bruli/php-git-hooks#47]
Hi,
setting the minimum version requirement to 5.6 in 2.4 is a bit of a problem. Since e.g. symfony requirements are 5.3.9 and my current version on my (hosted!) servers is 5.5.x.
Please keep in mind that some versions of php (namely 5.5) are maintained longer by the e.g. ubuntu team than the php developers.
This keeps me from using the git hooks with sf 2.8 and 3.0 since the component requirements you use are sf 3.0 branch but the min php version is too high.

**Comment by bruli** [comment]
phpunit requires php 5.6. So you need this version to use this tool.
