### ISSUE TITLE
Could not open input file: bin/php-cs

### ISSUE THREAD

**Issue by dufoli** [bruli/php-git-hooks#48]
I have an error in first run:
Checking code style with PHPCS....................Could not open input file: bin/phpcs

it seems to be located in vendor/bin/phpcs but it do not find it.
I try to install phpcs in my system but it seems that it is the one who wome with it which is expected.
```
my composer:
{
  "require-dev": {
    "phpunit/phpunit": "~5.0",
    "guzzle/guzzle": "3.9.3",
    "squizlabs/php_codesniffer": "2.5.0",
    "bruli/php-git-hooks": "~3.0"
  }
}
```
I just do composer install and update.
The composer configuration do not been display during install so I use a manuall php-git-hooks.yml:
here is the content
```
pre-commit:
  enabled: true
  execute:
    php-cs-fixer:
        enabled:    false
        levels:
            psr0:     true
            psr1:     true
            psr2:     true
            symfony:  true

    phpunit:
        enabled:        false
        random-mode:    true
    phplint:        false
    phpcs:
        enabled:    true
        standard:   PSR2
    phpmd:          true
    composer:       false
  message:
    right-message: 'HEY, GOOD JOB!!'
    error-message: 'FIX YOUR FUCKING CODE!!'
commit-msg:
    enabled:       true
    regular-expression: '#[0-9]{2,7}|#[0-9a-zA-Z]+-[0-9]+|hotfix'
```
if I enable php-cs-fixer I have same error with it:
Could not open input file: bin/php-cs-fixer 

I found nothing about it in other tickets

**Comment by bruli** [comment]
Phpcs command is created by php_codesniffer library.

You can delete bind and vendor directories and execute composer install again.

This re-create bin dir with links from tools.

**Comment by dufoli** [comment]
it still not work.
If I change bin/phpcs to vendor/bin/phpcs in codeSnifferHandler it work.
$processBuilder = new ProcessBuilder(array('php', 'vendor/bin/phpcs', '--standard='.$this->standard, $file));

But it seems that all call to binary needs that change

**Comment by dufoli** [comment]
we use symfony 1.4, can it be the reason ?

**Comment by bruli** [comment]
Of course. Please read REAME.md

**Comment by Umkus** [comment]
@bruli 

Sorry to necrobump, but I got the exactly same issue with `4.3` on php `7.0.8` and  symfony `3.1.2`.
Just like @dufoli pointed out, what actually ends up being run is `php bin/phpcs ...`, not `vendor/bin/`, where all binaries are.

I'm guessing this is because (at least in my case) [this condition](https://github.com/bruli/php-git-hooks/blob/master/src/PhpGitHooks/Infrastructure/Tool/ToolPathFinder.php#L29) never resolves to `true`. 

The `installedPackages` property is always empty and never used outside of this class.

So there's never a chance to run the scripts for the `vendor/bin`. Php only attempts to run the `bin/whatever` and obviously fails.

**Comment by bruli** [comment]
bin directory is a symblink from scripts in vendor.

```
 php-git-hooks git:(master) ls -l bin 
total 4
lrwxrwxrwx 1 pablo pablo 40 feb  2 11:17 composer -> ../vendor/composer/composer/bin/composer
lrwxrwxrwx 1 pablo pablo 36 feb  2 11:17 jsonlint -> ../vendor/seld/jsonlint/bin/jsonlint
lrwxrwxrwx 1 pablo pablo 41 mar  8 15:38 pdepend -> ../vendor/pdepend/pdepend/src/bin/pdepend
lrwxrwxrwx 1 pablo pablo 50 jun  6 09:58 phpcbf -> ../vendor/squizlabs/php_codesniffer/scripts/phpcbf
lrwxrwxrwx 1 pablo pablo 49 jun  6 09:58 phpcs -> ../vendor/squizlabs/php_codesniffer/scripts/phpcs
lrwxrwxrwx 1 pablo pablo 48 jun 15 11:30 php-cs-fixer -> ../vendor/friendsofphp/php-cs-fixer/php-cs-fixer
lrwxrwxrwx 1 pablo pablo 35 jun  6 09:57 phpmd -> ../vendor/phpmd/phpmd/src/bin/phpmd
lrwxrwxrwx 1 pablo pablo 33 jun 15 11:30 phpunit -> ../vendor/phpunit/phpunit/phpunit
lrwxrwxrwx 1 pablo pablo 62 jun  6 09:57 phpunit-randomizer -> ../vendor/fiunchinho/phpunit-randomizer/bin/phpunit-randomizer
lrwxrwxrwx 1 pablo pablo 53 mar  8 15:38 validate-json -> ../vendor/justinrainbow/json-schema/bin/validate-json
```
How do you install it?, by composer?. In this case you must have a bin dir with symblinks.

**Comment by Umkus** [comment]
Yes, I installed it through composer. 
I'm not sure about what bin dir you refer to exactly, but I got two app's and vendor's.
The app's one doesn't get populated with any symlinks from composer.
The vendor's one is never used by `php-git-hooks`.

Here's what I have: 
![Structure](https://i.imgur.com/ack4AWf.png)

I did manage to make it work by changing [this line](https://github.com/bruli/php-git-hooks/blob/master/src/PhpGitHooks/Infrastructure/Tool/ToolPathFinder.php#L38) to have not `bin`, but `vendor/bin`. 
Alternatively, yeah, create all the required links manually.

**Comment by bruli** [comment]
Could you paste your composer.json?

**Comment by Umkus** [comment]
The issue was in omitting the `bin-dir` setting, as the readme suggests.

**Comment by bruli** [comment]
If you set in your composer.json file:

'''json
"config": {
    "bin-dir": "bin"
  },
''´

And you remove your vendor dir, and execute composer install, you will have a bin dir (vendor/dir) with all symblinks.

**Comment by bruli** [comment]
Sorry.

Symfony projects, by defaults, has bin-dir config in his composer.json.

Maybe, now, this entry not exists. I'm creating a new project to test it and I can't view it.

**Comment by Umkus** [comment]
> And you remove your vendor dir, and execute composer install, you will have a bin dir (vendor/dir) with all symblinks.

This was exactly the issue. As soon as you have your bins _anywhere_ except the `bin/` dir, git hooks are not going to work. Since they are hardcoded to use that path.

So, maybe, the proper fix would be to use the `vendor/bin` path by default, _unless_ a custom `bin-dir` setting is used in `composer.json`. Then use that one instead.

**Comment by bruli** [comment]
Sorry, i wrote badly.

Default "bin dir" exists in your root project path. In your vendor dir is not correct.

If you add ...

"config": {
"bin-dir": "bin"
},

in your composer.json you will have a bin dir in your root path.

Everybody use it. I can not change it for you.

Sorry.

**Comment by Umkus** [comment]
Sure, I already added the `bin-dir` and set it to "bin/", and git hooks work fine now!

My only problem was (as outlined in the #69) with the readme file.

You wrote this about the `bin-dir` configuration:
> This is not necessary for Symfony projects.

But it is very, very necessary. It doesn't work if you don't have it 😃

**Comment by bruli** [comment]
Yes, because symfony project had by default "bin-dir" entry in composer.json. But now not exists. I will update README.md file.

**Comment by Umkus** [comment]
Cool! Thanks for your great work!
