### ISSUE TITLE
Allow for custom phpcs standard

### ISSUE THREAD

**Issue by rrajkomar** [bruli/php-git-hooks#57]
Currently it seems the project will not allow to use any other value than those in the STANDARDS_LIST.
However one could have a project with a custom set of rules for phpcs in which case this library cannot be used because it will not allow for a specified directory location as standard.

**Comment by JLepeltier** [comment]
you can use the defaults : phpcs.xml or phpcs.xml.dist and let the standard value as null
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file
