### ISSUE TITLE
Error when running PHP 7.1

### ISSUE THREAD

**Issue by nilportugues** [bruli/php-git-hooks#68]
When doing composer install on a Symfony app using PHP 7.1, I got the following error: 

```
  [PhpGitHooks\Module\Shared\Contract\Exception\InvalidBooleanException]  
  Invalid boolean value <>  
```

**Comment by bruli** [comment]
Try to remove your php-git-hooks.yml file and execute again composer install

**Comment by nilportugues** [comment]
it works
