### ISSUE TITLE
Error when commiting

### ISSUE THREAD

**Issue by nikophil** [bruli/php-git-hooks#80]
Hello,

when i try to commit after installing your app, i got the following error : 
PHP Fatal error:  Cannot redeclare class AppKernel in /home/nphilippe/works/les3vallees-bf/vendor/bruli/php-git-hooks/app/AppKernel.php on line 10

any help ?

thanks.

**Comment by xocasdashdash** [comment]
@nikophil I just found a workaround this issue, the problem is that the AppKernel here is not namespaced so it conflicts with the AppKernel of almost all of the symfony apps. My workaround was to rename my AppKernel class to something more project specific.

**Comment by bruli** [comment]
I'm ussing  into symfony projects and I haven't any problem with it.
Maybe you need clean your cache. Php-git-hook cached  all DIC data like Symfony.

**Comment by xocasdashdash** [comment]
Just run the following:
- Undo Kernel rename
- rm - rf app/cache/*
- ./.git/hooks/pre-commit: Fatal error: Cannot redeclare class AppKernel in vendor/bruli/php-git-hooks/app/AppKernel.php on line 10

The AppKernel class is this project is in the global namespace, same deal as the AppKernel that Symfony uses. That's where the conflict comes from or that's my understanding of it
