### ISSUE TITLE
Problem with ComposerTool

### ISSUE THREAD

**Issue by xocasdashdash** [bruli/php-git-hooks#82]
When you modify composer.json but you don't modify composer.lock (ie: adding a new file to the loaders) the tool complains because of the code on the  executeTool function of ComposerTool.php

**Comment by bruli** [comment]
If you modify your json file, always, you should update your lock file.

You can update it without update vendors with --lock option. I.e.: composer update --lock

**Comment by xocasdashdash** [comment]
Would you be open to a PR improving docs?

**Comment by bruli** [comment]
You can create a new PR if you want.

**Comment by abacaphiliac** [comment]
i think this has become a real issue in newer versions of composer, where `hash` has been replaced by `content-hash`.

@bruli you are correct that if the package requirements change then the lock file should be committed, but if you only update keywords, suggestions, or scripts then `composer update --lock` has no effect.
