### ISSUE TITLE
PHPUnit 6.x Support

### ISSUE THREAD

**Issue by nexeck** [bruli/php-git-hooks#86]
Is it possible to support the current stable PHPUnit 6.x Version?

**Comment by bruli** [comment]
Off course. I'm updating.

**Comment by nexeck** [comment]
@bruli Any update on this?

**Comment by nexeck** [comment]
Does this fixes the problem? https://github.com/padraic/mockery/pull/691

I have opened a issue for mockery, but phpunit 5.7 is just a dev dependecy in mockery.
https://github.com/padraic/mockery/issues/702
