### ISSUE TITLE
Why use --dry-run option?

### ISSUE THREAD

**Issue by Ovski4** [bruli/php-git-hooks#9]
Hi,
I noticed than the php-cs-fixer isn't fixing anything but it merely displays the incorrect files. I looked in your code to find in https://github.com/bruli/php-git-hooks/blob/master/src/PhpGitHooks/Infrastructure/PhpCsFixer/PhpCsFixerHandler.php line 38, that you use --dry-run option.
I just would like to understand why you use this option instead of actually fixing the file, since the php-cs command will sniff the same errors just after.
Thanks!

**Comment by bruli** [comment]
Hi.
The purpose of the tool is checking all code commited, never modify our code changes. If we don't use --dry-run option in php-cs-fixer, git extract modified files out current commit.
