### ISSUE TITLE
How to specify a custom "standard" file (ruleset.xml)

### ISSUE THREAD

**Issue by expertcoder** [bruli/php-git-hooks#96]
I have a `php-git-hooks.yml` config file like this

```
pre-commit:
  enabled: true
  execute:
    phpcs:
        enabled:     true
        standard:    my-custom-cs.xml
```

and I get this error

```
[PhpGitHooks\Module\Configuration\Contract\Exception\InvalidPhpCsStandardException]  
 Invalid phpcs standard <my-custom-cs.xml>
```

Any way to set a custom standard file (ruleset.xml) ?

Judging by the libraries code at https://github.com/bruli/php-git-hooks/blob/528a9a4c5905e9f5ca7bdb55f5111dd4fe22ca9c/src/PhpGitHooks/Module/Configuration/Domain/PhpCsStandard.php#L22 this may not be possible at the moment?

https://stackoverflow.com/questions/44424098/how-to-specify-custom-standard-with-bruli-php-git-hooks-library

Thanks.

**Comment by bruli** [comment]
It needs a little fix. I will do or you can send a PR.

**Comment by expertcoder** [comment]
Ill send a pull request when I can. thanks.

**Comment by expertcoder** [comment]
It appears this issue has already been corrected?

**Comment by bruli** [comment]
It's already corrected in master. I will create a new version to use it.
