### ISSUE TITLE
Add phpcpd integration

### ISSUE THREAD

**Issue by 0m3r** [bruli/php-git-hooks#98]
Please add phpcpd tool integration
[Copy/Paste Detector (CPD) for PHP code](https://github.com/sebastianbergmann/phpcpd)

**Comment by bruli** [comment]
Do you think it made sense?.

Git hook runs tool for commited files. I think phpcpd needs analize all code, and maybe will be to much slow.

**Comment by 0m3r** [comment]
You're right.
But you can always choose - no. [Y/n]
Or let it be in the pre-push section.

**Comment by bruli** [comment]
I'm thinking to create a new tool to run all php tools (phpunit, php-cs-fixer, phpmd, etc) in a single command, instead of git hook.

Maybe it make more sense in it.
